apiVersion: apps/v1
kind: Deployment
metadata:
  name: convtemp-dplmnt
  labels:
    app: convtemp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: convtemp
    template:
      metadata:
        labels:
          app: convtemp
      spec:
        containers:
        - name: conversaotemperatura
          image: raphaelcrejo/jde-conversao-temperatura:latest
          env:
          - name: PORT
            value: "8080"
          ports:
          - containerPort: 8080